
package eti.niwa.wektorianie.client.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SVGService", targetNamespace = "http://wektorianie.niwa.eti/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SVGService {


    /**
     * 
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processPicture", targetNamespace = "http://wektorianie.niwa.eti/", className = "eti.niwa.wektorianie.client.soap.ProcessPicture")
    @ResponseWrapper(localName = "processPictureResponse", targetNamespace = "http://wektorianie.niwa.eti/", className = "eti.niwa.wektorianie.client.soap.ProcessPictureResponse")
    @Action(input = "http://wektorianie.niwa.eti/SVGService/processPictureRequest", output = "http://wektorianie.niwa.eti/SVGService/processPictureResponse")
    public String processPicture(
        @WebParam(name = "data", targetNamespace = "")
        byte[] data);

    /**
     * 
     * @param filename
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processPictureByFilename", targetNamespace = "http://wektorianie.niwa.eti/", className = "eti.niwa.wektorianie.client.soap.ProcessPictureByFilename")
    @ResponseWrapper(localName = "processPictureByFilenameResponse", targetNamespace = "http://wektorianie.niwa.eti/", className = "eti.niwa.wektorianie.client.soap.ProcessPictureByFilenameResponse")
    @Action(input = "http://wektorianie.niwa.eti/SVGService/processPictureByFilenameRequest", output = "http://wektorianie.niwa.eti/SVGService/processPictureByFilenameResponse")
    public String processPictureByFilename(
        @WebParam(name = "filename", targetNamespace = "")
        String filename);

}
